import Link from 'next/link'

import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [
  {href: '/', label: 'Home'},
  {href: '/docs', label: 'Docs'},
  {href: '/todos', label: 'Todos'}
]

/** One thing in NextJS app you need to have is a root Layout,
 *  but the name RootLayout itself is arbitrary */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <ul className={inter.className}>
              {links.map( link => (
                <li>
                  <Link href={link.href}>{link.label}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        <h1>H1 title from root layout.tsx</h1>
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
